labs14-market-organizer/frontend

- package.json
- yarn.lock
-axios
-material-ui
-react-router-dom
-react-redux
-redux-thunk
-styled-components
Added some modules that our project will use
> Packages added that we'll need:

- .vscode/settings.json
- src/routes/AuthenticatePage.js
Auth bug, need to test in staging.
> test Auth page created

- src/routes/AuthenticatePage.js
- src/scss/authenticationPage.scss
> mobile styling added to auth page

- src/routes/AuthenticatePage.js
- src/scss/authenticationPage.scss
> Authentication page

- src/routes/TokenCollect.js
trying to fix a redirect issue where redirect fires on netlify incorrectly
removed redirects for debuging
> Add redux and routing

- src/routes/AuthenticatePage.js
Took out anchor tag and added href in material ui button.  It works and looks like other buttons
Button looks same as others now.
> fixed button href and took out anchor tag

- package.json
- src/tests/test.test.js
- yarn.lock
Add jest to the project and verify instalation
> Add jest testing to project

- src/App.js
- src/routes/UserOnboarding.js
Styling for this page is complete for mobile view.  Still needs the top portion which will be brought in as a component.  Also, still need Link hooked up for vendor page.
> User onboarding

- src/App.js
- src/assets/add.svg
- src/redux/actions/marketData.js
- src/redux/reducers/index.js
- src/redux/reducers/marketData.js
- src/redux/utls/axiosWithAuth.js
- src/redux/utls/hostUrl.js
- src/routes/CreateMarket.js
- src/routes/CreateVendor.js
- src/routes/ViewMyMarket.js
- src/scss/CreateMarket.scss
> View my market

- package.json
- src/redux/actions/mixpanel.js
- src/routes/MarketingPage.js
- yarn.lock
> mixpanel added and working

- package.json
- src/App.js
- src/index.js
- src/redux/actions/marketData.js
- src/redux/reducers/index.js
- src/redux/reducers/marketData.js
- src/redux/utls/store.js
- src/routes/Market-Redux-forms.js
- yarn.lock
Added redux forms to the project and hooked up create market page.
> Add redux forms

- src/App.js
- src/redux/actions/boothData.js
- src/redux/reducers/boothData.js
- src/redux/reducers/index.js
- src/routes/AddBooths.js
- src/routes/Booths-Redux-forms.js
- src/routes/CreateMarket.js
> Add booths

- src/App.js
- src/assets/border-color-24-px.svg
- src/redux/actions/boothData.js
- src/redux/actions/marketData.js
- src/redux/reducers/boothData.js
- src/routes/Booths-Redux-forms.js
Repull of the branch to add redux-forms to booths.
> replaced test with Booth endpoint

- src/App.js
- src/redux/actions/boothData.js
- src/redux/actions/marketData.js
- src/redux/actions/searchMarkets.js
- src/redux/actions/userData.js
- src/redux/actions/vendorData.js
- src/redux/reducers/userData.js
- src/routes/Booths-Redux-forms.js
- src/routes/MainPage.js
- src/routes/UserOnboarding.js
- src/routes/ViewMyMarket.js
> Add routing

- src/assets/ic-arrow-back.svg
- src/redux/actions/boothData.js
- src/routes/Booths-Redux-forms.js
- src/routes/SearchMarkets.js
- src/scss/ReduxForm.scss
> Addbooths delete

- src/redux/actions/marketData.js
- src/routes/Market-Redux-forms.js
> Fix update market

- src/routes/ViewMyMarket.js
> fixed bug on twitter site for viewmymaret

- src/App.js
- src/redux/actions/marketData.js
- src/routes/MainPage.js
- src/routes/VendorProfile.js
- src/routes/ViewMyMarket.js
> added vendorprofile page

- src/routes/Booths-Redux-forms.js
- src/routes/Market-Redux-forms.js
- src/routes/Vendor-Redux-forms.js
- src/routes/VendorProfile.js
- src/routes/ViewMyMarket.js
> Links arrow

- src/App.js
- src/components/Navbar.js
- src/routes/PrivacyPolicy.js
Add Privacy Policy page to site at `/privacy`
> Privacy policy

- src/App.js
- src/components/Navbar.js
- src/routes/PrivacyPolicy.js
- src/routes/TermsAndConditions.js
Adds a Terms & Conditions page to the site.
> Terms & Conditions

- src/redux/actions/marketData.js
- src/redux/actions/vendorData.js
- src/routes/Booths-Redux-forms.js
- src/routes/SearchMarkets.js
- src/routes/UserOnboarding.js
- src/routes/Vendor-Redux-forms.js
- src/routes/VendorProfile.js
- src/routes/ViewMyMarket.js
added mixpanel to track whether user picks create vendor or create market
> Mixpanel tests

- src/components/NavbarMarket.js
- src/routes/MarketingPage.js
- src/routes/MeetTheTeam.js
Landing & Meet the team page more responsive at lower resolutions. 
> Landing & Meet the team page more responsive at lower resolutions. 

- src/components/Navbar.js
- src/components/NavbarMarket.js
- src/routes/MarketingPage.js
- src/routes/MeetTheTeam.js
> Nav buttons working for terms and privacy

- src/components/Navbar.js
- src/components/NavbarMarket.js
- src/redux/utls/hostUrl.js
- src/routes/Booths-Redux-forms.js
made styling changes to add booth.  
> Add boooth

- src/App.js
- src/redux/actions/marketData.js
- src/redux/actions/userData.js
- src/redux/actions/vendorData.js
- src/routes/Market-Redux-forms.js
- src/routes/NormalizePhone.js
- src/routes/SearchMarkets.js
- src/routes/TokenCollect.js
- src/routes/Vendor-Redux-forms.js
- src/routes/ViewMyMarket.js
update create market page and create vendor page to add contact info.  Also added market rules to the create market page.
> Adding contact

- src/redux/actions/userData.js
- src/redux/reducers/userData.js
- src/redux/utls/axiosWithAuth.js
- src/routes/TokenCollect.js
made changes to clear local storage if a token is expired to prevent hangups.
> ability to clear local storage if token expired

- src/App.js
- src/routes/MarketRules.js
built a market rules page/ needs hooked up to redux.
> Market rules

- src/routes/VendorProfile.js
styling for vendor profile completed.
> styling for vendor profile done

- src/App.js
- src/components/Navbar.js
- src/components/NavbarVendor.js
- src/redux/actions/vendorData.js
- src/routes/CreateVendor.js
- src/routes/SearchMarkets.js
- src/routes/Vendor-Redux-forms.js
Bug in adding items to vendor fixed. Styled to design/ slight modifications
> Troube shooting items

- src/components/Navbar.js
- src/redux/actions/userData.js
- src/redux/utls/hostUrl.js
- src/routes/CreateVendor.js
- src/routes/Vendor-Redux-forms.js
added items to state equaling items: [""] to allow input to pop up originally
commented out createvendor.js
> Refresh tokens

- src/components/Navbar.js
- src/components/NavbarVendor.js
Fixed a couple bugs in the nav on the vendor side.
> Vendor nav fix

- src/components/MarketDay.js
- src/components/NavbarMarket.js
- src/components/VendorsRentedByDay.js
date formated to be more user friendly.
> Mo viewing

- src/App.js
> took out console.logs

- src/components/VendorsRentedByDay.js
centered info on screen at full width
> center the info for vendors on full screen

- src/components/VendorsRentedByDay.js
fade in for the market owners list of vendors who have rented a booth by day.
> fade in working

- src/components/VendorsRentedByDay.js
- src/redux/utls/hostUrl.js
- src/routes/AuthenticatePage.js
> added login with square button and changed hostUrl to dynamic

- src/components/VendorsRentedByDay.js
added in the booths that werent rented so the market owner can see the booths and how many are available
> New upcoming
